name: chrip_aid
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.2

  # Navigator
  go_router: ^9.0.0

  # Json Annotation
  json_annotation: ^4.9.0

  # REST Api
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  logger: ^2.4.0

  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # Local Storage
  universal_html: ^2.2.3

  # dotenv
  flutter_dotenv: ^5.1.0

  # DI
  flutter_riverpod: ^2.3.6

  # Internationalization
  intl: ^0.19.0

  # Calender
  table_calendar: ^3.0.9

  # Validator
  validators: ^3.0.0

  # FCM (Firebase Messaging)
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_messaging_web: ^3.5.18
  flutter_local_notifications: ^17.2.3

  # Google Map
  google_maps_flutter: ^2.2.1
  flutter_google_places: ^0.3.0
  google_maps_flutter_android: ^2.5.1
  google_maps_flutter_platform_interface: ^2.4.1
  google_maps_webservice: ^0.0.19
  google_geocoding: ^0.2.0

  # Percent indicator 추가
  percent_indicator: ^4.2.3
  step_progress_indicator: ^1.0.2
  sleek_circular_slider: ^2.0.1
  progress_indicators: ^1.0.0
  liquid_progress_indicator: ^0.4.0

  # Sliding Up Panel
  flutter_sliding_up_panel: ^2.1.1

  # Get 패키지 사용
  get: ^4.1.4

  # Image
  image_picker: ^1.0.4
  card_swiper: ^3.0.1
  photo_view: ^0.15.0

  # Collection, HTTP, AWS
  collection: ^1.17.1
  http: ^0.13.6
  aws_s3_upload: ^1.5.0
  extended_image: ^8.0.2
  android_intent_plus: ^5.1.0
  socket_io_client: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # REST Api
  build_runner: ^2.4.6
  retrofit_generator: ^9.1.2
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/pajukids_house.jpg
    - assets/image/choco_pie.jpg
    - .env